### ISSUE TITLE
Token

### ISSUE THREAD

**Issue by JoanManelRamirezCuart** [CIFP-Pau-Casesnoves-DAW/etv-public-francesc-adrian-albert-xisco#1]
No puedo añadir el token el la pagina para probar la api

**Comment by ADCP-dev** [comment]
El error de no poder introducir el token esta solucionado
![image](https://user-images.githubusercontent.com/78976993/219726301-d4baebfb-f973-45eb-866b-3b4cdfb6b8c7.png)
