### ISSUE TITLE
Accomodations

### ISSUE THREAD

**Issue by DeviLopez** [CIFP-Pau-Casesnoves-DAW/etv-public-francesc-adrian-albert-xisco#3]
la forma de crear los alojamientos no queda muy claro para hacer la petición ya que están las claves fk por el medio

**Comment by albertpll** [comment]
Se ha solucionado el error en la documentación de la api.
![image](https://user-images.githubusercontent.com/100235197/219727880-471fa7ef-e6bb-47c0-81c8-bd6e6ebba1da.png)
